config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations'}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :homepage 
  resources :grounds do
    resources :books
    resources :reviews
    resources :favorites
  end
  resources :users
  

  get '/callback' => 'session#create'
  get '/login' => 'session#login'
  root 'homepage#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify :before_add => :before_add_method
  after_create :assign_default_role

  def before_add_method(role)
    # do something before it gets added
  end

  def assign_default_role
    # self.add_role(:player) if self.roles.blank?
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :books
  has_many :reviews
  has_many :favorites

  has_one_attached :profile_image

  attr_writer :login
  validate :validate_username
  validates_uniqueness_of :username

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.from_omniauth(auth) 
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session) 
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user  is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if  is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController


  def create
    super

    if current_user
      current_user.profile_image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default_profile.png")), filename: 'default_profile.png' , content_type: "image/jpg")
    end

    if current_user
      if params[:role] == "player"
        current_user.add_role :player
      elsif params[:role] == "proprietor"
        current_user.add_role :proprietor
      end
    end
  end

  
  def destroy
    @reviews = Review.all.where(:user_id => current_user.id)
    @reviews.each do |review|
      @ground = Ground.find(review.ground_id)
      @ground.ratingNum = @ground.ratingNum - 1
      @ground.ratingSum = @ground.ratingSum - review.rating
      @ground.save!
    end
    @reviews.destroy_all

    @books = Book.all.where(:user_id => current_user.id)
    @books.each do |book|
      book.user_id = nil
      book.save!
    end

    if current_user.has_role? :proprietor
      grounds = Ground.with_role(:owner, current_user) #Prendo tutti i ground dell'utente che si vuole cancellare
      grounds.each do |ground| #Per ognuno di essi
        books = Book.with_role(:owner, current_user).where(:ground_id => ground.id) #Prendo tutte le sue prenotazioni
        books.each do |book| #Per ognuna di esse
          Timetable.all.where(:id => book.timetable_id).destroy_all #Ne elimino il timatable
          book.destroy #Elimino tutte le prenotazioni del proprietario
        end
        ground.destroy #Elimino tutti i grounds del proprietario
      end
    end
    
    super
  end

  def update
    super

    current_user.profile_image.attach(params[:profile_image])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    
  end
  
  def show
    @current_user = User.all.where(["id LIKE ?", "#{current_user.id}"]).first
  end

  def edit
    
  end
  
end

app/views/users/show.html.erb
<style>

  body{
      color: black;
      margin: 0px;
  }

  .all{
      margin-left: 30%;
  }
  
  .settings{
      color: gray;
      width: 30px;
      height: 30px;
  }

  .title-td{
      padding: 5px;
  }

  .favorites-table{
      margin-left: 70px;
  }

  .books-td{
      padding: 5px;
  }

  .btn-ground{
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      background-color: #c12400;
      font-weight: bold;
      color:white;
      cursor: pointer;
  }
  .btn-ground:hover{
      background-color: #b52100;
  }

  .profile-image{
      width: 100px;
      height: 100px;
      border-radius: 50%;
  }

  .settings{
      opacity: 0.8;
  }
  .settings:hover{
      opacity: 1;
  }

  .link-color{
      color: blue;
  }
  .link-color:hover{
      color: darkblue;
  }
</style>

<body>

  <div class="all">
    <div class="title">
      <table>
	<tr>
	  <td class="title-td"><%= link_to image_tag('settings.png', class: "settings"), edit_user_registration_path(current_user.id) %></td>
	  <td class="title-td"><h2> <%= @current_user.username  %></h2></td>
	  <td class="title-td"><h2> (<%= @current_user.email%>)  </h2></td>
	  <td><image src="<%=(url_for(current_user.profile_image))%>" class="profile-image" /></td>
	</tr>
      </table>
    </div>

    <div class="user-info">
      <table>
	<tr>
	  <td valign="top">
	    <% if (current_user.has_role? :proprietor) || (current_user.has_role? :admin) %>
	    <table>
	      <tr>
		<td style="text-align: center;"><h2><%= @current_user.roles.where(:name => "owner", :resource_type => "Ground").count %> Campi posseduti:</h2></td>
	      </tr>
	      <tr>
		<td>
		  <table>
		    <tr>
		      <td class="books-td"></td>
		      <td class="books-td"><b> Nome del campo </b></td>
		    </tr>
		    <% Ground.with_role(:owner, current_user).each do |ground| %>
		    <tr>
		      <td class="books-td"> <%= link_to "Modifica", edit_ground_path(ground.id), class: "link-color"%> </td>
		      <td class="books-td"> <%= link_to ground.title, ground_path(ground.id), class: "link-color" %> </td>
		    </tr>
		    <% end %>
		  </table>
		</td>
	      </tr>
	    </table>
	    <% end %>
	    <% if (current_user.has_role? :player) || (current_user.has_role? :admin) %>
	    <table>
	      <tr>
		<td style="text-align: center;"><h2><%= @current_user.books.count %> Prenotazioni:</h2></td>
	      </tr>
	      <tr>
		<td>
		  <table>
		    <tr>
		      <td class="books-td"></td>
		      <td class="books-td"><b> Nome del campo </b></td>
		      <td class="books-td"><b> Orario </b></td>
		    </tr>
		    <% @current_user.books.each do |book| %>
		    <tr>
		      <td class="books-td"> <%= link_to "Rimuovi", ground_book_path(:id => book.id, :ground_id => Ground.all.where(:id => book.ground_id).first.id)+"?book_action=remove", :method => :put, class: "link-color" %> </td>
		      <td class="books-td"> <%= link_to Ground.all.where(:id => book.ground_id).first.title, ground_path(Ground.all.where(:id => book.ground_id).first.id), class: "link-color" %> </td>
		      <td class="books-td"> <%= Timetable.all.where(:id => book.timetable_id).all.first.from %>:00 - </td>
		      <td> <%= Timetable.all.where(:id => book.timetable_id).all.first.to %>:00 </td>
		    </tr>
		    <% end %>
		  </table>
		</td>
	      </tr>
	    </table>
	    <% end %>
	  </td>
	  <td valign="top">
	    <table class="favorites-table">
	      <tr>
		<td><h2><%= @current_user.favorites.count %> Preferiti:</h2></td>
	      </tr>
	      <tr>
		<td>
		  <table>
		    <tr>
		      <td class="books-td"><b> Nome del campo </b></td>
		    </tr>
		    <% @current_user.favorites.each do |favorite| %>
		    <tr>
		      <td class="books-td"> <%= link_to Ground.all.where(:id => favorite.ground_id).first.title,  ground_path(Ground.all.where(:id => favorite.ground_id).first.id), class: "link-color" %> </td>
		    </tr>
		    <% end %>
		  </table>
		</td>
	      </tr>
	    </table>
	  </td>
	</tr>
      </table>
      <% if (current_user.has_role? :proprietor) || (current_user.has_role? :admin)%>
      <%= button_to "Aggiungi campo sportivo", new_ground_path, :method => 'get', class: 'btn-ground' %>
      <% end %>
      
    </div>
    
  </div>
  
</body>