config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'users/registrations'}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :homepage 
  resources :grounds do
    resources :books
    resources :reviews
    resources :favorites
  end
  resources :users
  

  get '/callback' => 'session#create'
  get '/login' => 'session#login'
  root 'homepage#index'
end

app/models/ground.rb
class Ground < ApplicationRecord

  resourcify

  has_many :books
  has_many :reviews
  has_many :favorites

  has_one_attached :ground_image
end

app/controllers/grounds_controller.rb
# coding: utf-8
class GroundsController < ApplicationController


  def index
    grounds = Ground.all
    if "#{params[:search]}" != ""
      grounds = grounds.where(["title LIKE ?","%#{params[:search]}%"])
    end
    if "#{params[:priceFrom]}" != ""
      grounds = grounds.where(["price >= ?", "#{params[:priceFrom]}".to_i])
    end
    if "#{params[:priceTo]}" != ""
      grounds = grounds.where(["price <= ?", "#{params[:priceTo]}".to_i])
    end
    if "#{params[:category]}" != "Qualsiasi"
      grounds = grounds.where(["category LIKE ?", "%#{params[:category]}%"])
    end
    @grounds = grounds
  end

  def show
    id = params[:id]
    @ground = Ground.find(id)

    @books = Book.all

    reviews = Review.all
    reviews = reviews.where(["ground_id LIKE ?", "#{params[:id]}"])
    @reviews = reviews
  end

  def new
    
  end
  
  def create
    @control_flag = false
    flash[:notice] = ""
    if (params[:title] == "")
      flash[:notice] += "• Il campo nome non può essere vuoto | "
      @control_flag = true
    end
    if (params[:price1] == "") && (params[:price2] == "")
      flash[:notice] += "• Non possono essere vuoti tutti e due i campi del prezzo | "
      @control_flag = true
    end
    if (params[:price1].to_i.to_s != params[:price1]) || (params[:price2].to_i.to_s != params[:price2]) #Questo metodo serve per verificare che i prezzi siano numero ma non è molto bello a vedersi
      flash[:notice] += "• I prezzi devono essere numeri | "
      @control_flag = true
    end
    if (params[:city] == "")
      flash[:notice] += "• Il campo città non può essere vuoto | "
      @control_flag = true
    end
    if (params[:address] == "")
      flash[:notice] += "• Il campo indirizzo non può essere vuoto | "
      @control_flag = true
    end
    if @control_flag
      redirect_to new_ground_path
    else
    
      if (current_user.has_role? :proprietor) || (current_user.has_role? :admin) #Possono creare nuovi campo i proprietor e l'admin, non i player
        price = params[:price1].to_f + (params[:price2].to_f/100)
        @ground = Ground.create!(:title => params[:title], :price => price, :city => params[:city], :address => params[:address], :description => params[:description], :category => params[:category])
        if params[:ground_image] != nil
          @ground.ground_image.attach(params[:ground_image])
        else
          @ground.ground_image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.jpg")), filename: 'default.jpg' , content_type: "image/jpg")
        end
        @ground.save!
        current_user.add_role :owner, @ground #Serve per associare il campo al proprietario, per evitare che un altro utente elimini un campo non suo
        redirect_to ground_path(@ground)
      else
        flash[:notice] = "Non ti è permesso creare campi sportivi!"
        redirect_to root_path
      end
      
    end
  end

  def edit
    
  end

  def update
    if (current_user.has_role? :proprietor) || (current_user.has_role? :admin) #Possono modificare i campi i proprietor e l'admin, non i player
      @ground = Ground.find(params[:id])
      if (current_user.has_role? :owner, @ground) || (current_user.has_role? :admin) #Il proprietor può modificare il campo sportivo solo se è suo
        if params[:price1] != "" || params[:price1] != ""
          price = params[:price1].to_f + (params[:price2].to_f/100)
          @ground.price = price
        end
        if params[:title] != ""
          @ground.title = params[:title]
        end
        if params[:city] != ""
          @ground.city = params[:city]
        end
        if params[:description] != ""
          @ground.description = params[:description]
        end
        if params[:category] != ""
          @ground.category = params[:category]
        end
        if params[:address] != ""
          @ground.address = params[:address]
        end
        if params[:ground_image] != nil
          @ground.ground_image.attach(params[:ground_image])
        end
        @ground.save!
        redirect_to ground_path(@ground)
      else
        flash[:notice] = "Non ti è permesso modificare campi sportivi degli altri!"
      redirect_to root_path
      end
    else
      flash[:notice] = "Non ti è permesso modificare campi sportivi!"
      redirect_to root_path
    end
  end

  def destroy
    id_ground = params[:id]
    @ground = Ground.find(id_ground)
    if (current_user.has_role? :owner, @ground) || (current_user.has_role? :admin) #Se l'utente è il possessore del campo allora può eliminarlo
      books = Book.with_role(:owner, current_user).where(:ground_id => id_ground)
      books.each do |book|
        Timetable.all.where(:id => book.timetable_id).destroy_all
        book.destroy #Elimino tutte le prenotazioni di quel campo
      end
      @ground.reviews.destroy_all #Elimino tutte le recensioni di quel campo
      @ground.favorites.destroy_all #Elimino tutte le preferenze di quel campo
      @ground.destroy
      redirect_to user_path(current_user.id)
    else
      flash[:notice] = "Non puoi eliminare i campi degli altri!"
      redirect_to root_path
    end
  end

end

app/helpers/grounds_helper.rb
module GroundsHelper
end

app/views/grounds/edit.html.erb
<style>
  html{
      background-color: #275a74;
      color: white;
  }

  .ground-form{
      position:fixed;
      top: 25%;
      left: 50%;
      width:45em;
      margin-top: -9em;
      margin-left: -25em;
      padding: 10px;
      border-radius: 25px;
      background-color: #24536b;
      padding-bottom: 25px;
  }
  .ground-content{
      position: relative;
      text-align: center;
  }
  .field{
      padding: 10px;
  }
  .btn-login{
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      background-color: #c12400;
      font-weight: bold;
      color:white;
      cursor: pointer;
  }
  .btn-login:active{
      background-color: #b52100;
  }
  .btn-login:hover{
      background-color: #b52100;
  }

  .category-select{
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
  }
  .price-text{
      width: 60px;
  }
  .description-text{
      width: 400px;
      height: 100px;
      resize: none;
  }
  
</style>

<div class="ground-form">
  <div class="ground-content">
    <h2 class="title">Modifica campo sportivo</h2>

    <%= form_tag ground_path(), :method => :put, multipart: true do %>
    
      <div class="field">
	<label>Categoria </label> <br />
	<select name="category" class="category-select">
	  <option value="Calcio"> Calcio </option>
	  <option value="Tennis"> Tennis </option>
	  <option value="Basket"> Basket </option>
	</select>
      </div>
      
      <div class="field">
	<%= label_tag "Nome del campo sportivo" %> <br />
	<%= text_field_tag :title, params[:title], autofocus: true%>
      </div>

      <div class="field">
	<%= label_tag "Prezzo" %><br />
	<%= text_field_tag :price1, params[:price1], class: "price-text" %> <b>,</b> <%= text_field_tag :price2, params[:price2], class: "price-text" %>€
      </div>

      <div class="field">
	<%= label_tag "Città" %> <br />
	<%= text_field_tag :city, params[:city] %>
      </div>

      <div class="field">
	<%= label_tag "Indirizzo" %> <br />
	<%= text_field_tag :address, params[:address] %>
      </div>

      <div class="field">
	<%= label_tag "Immagine" %><br />
	<%= file_field_tag :ground_image %>
      </div>

      <div class="field" >
	<%= label_tag :description %> <br />
	<%= text_area_tag :description, params[:description], class: "description-text" %>
      </div>

      <div class="actions">
	<%= submit_tag "Salva", class: "btn-login" %>
      </div>

      <% end %>
      
      <%= button_to "Aggiungi prenotazione", new_ground_book_path(params[:id]), :method => :get, class: "btn-login" %>
      
      <%= button_to "Elimina campo", ground_path(), :method => :delete, class: "btn-login" %>
  </div>
</div>

app/views/grounds/new.html.erb
<style>
  html{
      background-color: #275a74;
      color: white;
  }

  .ground-form{
      position:fixed;
      top: 30%;
      left: 50%;
      width:45em;
      margin-top: -9em;
      margin-left: -25em;
      padding: 10px;
      border-radius: 25px;
      background-color: #24536b;
      padding-bottom: 25px;
  }
  .ground-content{
      position: relative;
      text-align: center;
  }
  .field{
      padding: 10px;
  }
  .btn-login{
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      background-color: #c12400;
      font-weight: bold;
      color:white;
      cursor: pointer;
  }
  .btn-login:active{
      background-color: #b52100;
  }
  .btn-login:hover{
      background-color: #b52100;
  }

  .category-select{
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
  }
  .price-text{
      width: 60px;
  }
  .description-text{
      width: 400px;
      height: 100px;
      resize: none;
  }
  
</style>

<div class="ground-form">
  <div class="ground-content">
    <h2 class="title">Nuovo campo sportivo</h2>
    
    <p style="color: white; margin-left: 10px;"><%= flash[:notice] %></p>

    <%= form_tag grounds_path(), :method => :post, multipart: true do %>
    
      <div class="field">
	<label>Categoria </label> <br />
	<select name="category" class="category-select">
	  <option value="Calcio"> Calcio </option>
	  <option value="Tennis"> Tennis </option>
	  <option value="Basket"> Basket </option>
	</select>
      </div>
      
      <div class="field">
	<%= label_tag "Nome del campo sportivo" %> <br />
	<%= text_field_tag :title, params[:title], autofocus: true%>
      </div>

      <div class="field">
	<%= label_tag "Prezzo" %><br />
	<%= text_field_tag :price1, params[:price1], class: "price-text" %> <b>,</b> <%= text_field_tag :price2, params[:price2], class: "price-text" %>€
      </div>

      <div class="field">
	<%= label_tag "Città" %> <br />
	<%= text_field_tag :city, params[:city] %>
      </div>

      <div class="field">
	<%= label_tag "Indirizzo" %> <br />
	<%= text_field_tag :address, params[:address] %>
      </div>

      <div class="field">
	<%= label_tag "Immagine" %><br />
	<%= file_field_tag :ground_image %>
      </div>

      <div class="field" >
	<%= label_tag :description %> <br />
	<%= text_area_tag :description, params[:description], class: "description-text" %>
      </div>

      <div class="actions">
	<%= submit_tag "Aggiungi", class: "btn-login" %>
      </div>

    <% end %>
  </div>
</div>

app/views/grounds/show.html.erb
<html>
  <head>
    <style type="text/css">
      body{
	  color: black;
	  margin: 0px;
	  margin-bottom: 50px;
      }

      .title-container{
	  color: white;
	  position: relative;
	  background-color: #275a74;
	  padding: 25px;
	  text-align: center;
      }
      .title{
	  margin-top: 0%;
      }
      #prezzo{
	  color: gray;
	  font-size: 30px;
	  
      }
      .grounds-info{
	  margin-left: 25%;
      }
      .ground-element{
	  padding-top: 20px;
	  padding-bottom: 20px;
	  padding-right: 20px;
      }
      .td-description{
	  width: 512px;
	  padding-top: 10px;
	  padding-bottom: 10px;
	  border-bottom: 1px solid lightgray;
      }
      #hidden-link{
	  visibility: hidden;
      }
      span{
	  cursor: pointer;
	  font-size: larger;
      }

      #commentbtn{
	  
	  padding: 12px 20px;
	  margin: 8px 0;
	  display: inline-block;
	  border: 1px solid #ccc;
	  border-radius: 4px;
	  box-sizing: border-box;
	  background-color: #00008B;
	  font-weight: bold;
	  color:white;
	  cursor: pointer;
      }
      #commentbtn:hover{
	  background-color: #000080;
      }

      #comment{
	  border-radius: 0.5px;
	  resize: none;
	  width: 512px;
	  height: 150px;
      }
      .users-reviews{
	  margin-left: 25%;
      }
      .border-top-row{
	  border-top: 1px solid lightgray;
      }
      table{
	  border-collapse: collapse;
      }

      .day-choice{
	  padding: 12px 20px;
	  margin: 8px 0;
	  display: inline-block;
	  border: 1px solid #ccc;
	  border-radius: 4px;
	  box-sizing: border-box;
      }

      #search-timetable-btn{
	  padding: 12px 20px;
	  margin: 8px 0;
	  display: inline-block;
	  border: 1px solid #ccc;
	  border-radius: 4px;
	  box-sizing: border-box;
	  background-color: #c12400;
	  font-weight: bold;
	  color:white;
	  cursor: pointer;
      }
      #search-timetable-btn:hover{
	  background-color: #b52100;
      }

      .booking-div{
	  padding-top: 50px;
	  padding-bottom: 50px;
      }

      #book-link{
	  
	  padding-left: 15px;
      }

      .books-table{
	  margin-top: 10px;
      }

      #book-link{
	  padding: 10px;
      }

      .ratingStars{
	  width: 25px;
	  height: 25px;
	  padding-top: 20px;
	  padding-bottom: 20px;
	  
	  
      }
      .table-prova{
	  margin-left: 25px;
      }

      .ground-image{
	  width: 512px;
	  height: 350px;
      }
      .profile-image{
	  width: 70px;
	  height: 70px;
	  border-radius: 50%;
	  margin-top: 5px;
      }
      
    </style>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      .checked {
	  color: orange;
      }
      
    </style>
  </head>

  <body>
    <div class="title-container">
      <h1 class="title"><%= @ground.title %></h1>
    </div>
    <div class="grounds-info">
      
      <table id="fixedheight">
	<tr>
	  <td> <image src="<%=(url_for(@ground.ground_image))%>" class="ground-image"> </td>
	  <td>
	    <table class="table-prova">
	      <tr><td class="ground-element" id ="prezzo"><b><%= @ground.price %>€ </b></td></tr>
	      <% if @ground.ratingNum != 0 %>
	      <tr>
		<% if (@ground.ratingSum.to_f/@ground.ratingNum.to_f).round == 1 %>
		<td>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		</td>
		<% elsif (@ground.ratingSum.to_f/@ground.ratingNum.to_f).round == 2 %>
		<td>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		</td>
		<% elsif (@ground.ratingSum.to_f/@ground.ratingNum.to_f).round == 3 %>
		<td>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		</td>
		<% elsif (@ground.ratingSum.to_f/@ground.ratingNum.to_f).round == 4 %>
		<td>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "star.png", class: "ratingStars"%>
		</td>
		<% elsif (@ground.ratingSum.to_f/@ground.ratingNum.to_f).round == 5 %>
		<td>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		  <%= image_tag "yellow_star.png", class: "ratingStars"%>
		</td>
		<% end %>
	      </tr>
	      <% else %>
	      <tr><td class="ground-element"> <b>Voto</b>: Nessun voto </td></tr>
	      <% end %>
	      <tr><td class="ground-element"> <b>Città</b>: <%= @ground.city %> </td></tr>
	      <tr><td class="ground-element"> <b>Indirizzo</b>: <%= @ground.address %> </td></tr>
	    </table>
	  </td>
	</tr>
      </table>
      <table class="description">
	<tr class="border-top-row"><td style="padding-top: 10px;"><b> DESCRIZIONE </b></td></tr>
	<tr><td class="td-description"><%= @ground.description %></td></tr>
      </table>
      <% if (current_user.has_role? :proprietor) || (current_user.has_role? :admin) %>
      <table class="books-table">
	<% Book.with_role(:owner, current_user).where(:ground_id => params[:id]).each do |book| %>
	<tr>
	  <td style="color: green;"><b><%= book.timetable.from %>:00 - </b></td>
	  <td style="color: green;"><b><%= book.timetable.to %>:00 </b></td>
	  <td id="book-link"><b> <%= link_to "Rimuovi", ground_book_path(:id => book.id, :ground_id => params[:id]), :method => :delete %> </b></td>
	</tr>
	<% end %>
      </table>
      <% end %>
      <% if (current_user.has_role? :player) || (current_user.has_role? :admin) %>
      <div class="booking-div">
	<form class="search-time-form">
	  <select name="dayChoice" id="dayID" class="day-choice">
	    <option> Lunedì </option>
	    <option> Martedì </option>
	    <option> Mercoledì </option>
	    <option> Giovedì </option>
	    <option> Venerdì </option>
	    <option> Sabato </option>
	    <option> Domenica </option>
	  </select>
	  
	  <%= button_to "Cerca", grounds_path, :method => 'get', class: 'btn-search', id: "search-timetable-btn" %>
	  
	  <table class="books-table">
	    <% @books.each do |book| %>
	    <% if Timetable.find(book.timetable_id).day == params[:dayChoice] %>
	    <% if book.ground_id == params[:id].to_i %>
	    <% if book.user_id == nil %>
	    <tr>
	      <td style="color: green;"><b><%= book.timetable.from %>:00 - </b></td>
	      <td style="color: green;"><b><%= book.timetable.to %>:00 </b></td>
	      <td id="book-link"><b> <%= link_to "Prenota", ground_book_path(@ground, :timetable_id => book.timetable.id)+"&book_action=add", :method => :put %> </b></td>
	    </tr>
	    <% else %>
	    <tr>
	      <td style="color: red; padding: 10px;"><b><%= book.timetable.from %>:00 - </b></td>
	      <td style="color: red;"><b><%= book.timetable.to %>:00</b></td>
	    </tr>
	    <% end %>
	    <% end %>
	    <% end %> 
	    <% end %>
	  </table>
	</form>
      </div>


      <table class="review-table">
	<tr>
	  <td>
	    <!-- Qui c'è una tabella inutile che ho dovute mettere perché sennò il submit funziona solo se la pagina viene refreshata, è un problema di HTML (la form deve essere all'interno di una td) -->
	    <%= form_tag ground_reviews_path(params[:id]), :method => :post do %>
	    <table>
	      <tr><td>
		  <big><big><span class="fa fa-star checked" id="star1" onclick="ratingChecked1()"></span></big></big>
		  <big><big><span class="fa fa-star" id="star2" onclick="ratingChecked2()"></span></big></big>
		  <big><big><span class="fa fa-star" id="star3" onclick="ratingChecked3()"></span></big></big>
		  <big><big><span class="fa fa-star" id="star4" onclick="ratingChecked4()"></span></big></big>
		  <big><big><span class="fa fa-star" id="star5" onclick="ratingChecked5()"></span></big></big>
	      </td></tr>
	      <tr><td><%= text_area(:comment, :body, placeholder: "Scrivi una recensione", id: "comment", name: "review")%></td></tr>
	      <tr>
		<td><%= submit_tag "Commenta!", id: "commentbtn" %></td>
		<td>
		  <select name="rating" style="visibility: hidden;" id="ratingSelect">
		    <option value="1">1</option>
		    <option value="2">2</option>
		    <option value="3">3</option>
		    <option value="4">4</option>
		    <option value="5">5</option>
		  </select>
		</td>
	      </tr>
	    </table>
	    <% end %>
	  </td>
	</tr>
      </table>
      
      <% end %>
    </div>
    
    <div class="users-reviews">
      <h2> <%= @reviews.count %> Commenti: </h2>
      <table>
	<% @reviews.each do |review| %>
	<tr>
	  <table>
	    <% if review.user_id == current_user.id %>
	    <tr><td></td><td><%= link_to "Elimina commento", ground_review_path(:id => review.id, :ground_id => @ground.id), :method => :delete%></td></tr>
	    <% end %>
	    <tr class="border-top-row">
	      <td><image src="<%=(url_for(User.find(review.user_id).profile_image))%>" class="profile-image" /></td>
	      <td style="padding-top:20px; padding-left: 10px; padding-bottom:10px;  width: 512px; text-decoration: underline;"><b> <%= User.all.find(review.user_id).username %> </b></td>
	      <td style="padding-top:10px;"> Voto: <%= review.rating %> </td>
	    </tr>
	  </table>
	</tr>
	<table>
	  <tr><td style="padding-left:10px; padding-bottom:20px; width: 512px;"> <%= review.comments %> </td></tr>
	</table>
	<% end %>
      </table>
      
    </div>
    
  </body>
  
  <script>

    function addReview(){
	//Attraverso questo script attivo il link nascosto per andare nella pagina new della review
	localStorage.setItem("comment", document.getElementById("comment").value);
	if(document.getElementById("star5").className == "fa fa-star checked"){
	    localStorage.setItem("rating", "5");
	}else if(document.getElementById("star4").className == "fa fa-star checked"){
	    localStorage.setItem("rating", "4");
	}else if(document.getElementById("star3").className == "fa fa-star checked"){
	    localStorage.setItem("rating", "3");
	}else if(document.getElementById("star2").className == "fa fa-star checked"){
	    localStorage.setItem("rating", "2");
	}else{
	    localStorage.setItem("rating", "1");
	}

	document.getElementById("hidden-link").click();
    }

    function ratingChecked1(){
	if(document.getElementById("star1").className == "fa fa-star checked"){
	    document.getElementById("star5").className = "fa fa-star";
	    document.getElementById("star4").className = "fa fa-star";
	    document.getElementById("star3").className = "fa fa-star";
	    document.getElementById("star2").className = "fa fa-star";
	}else{
	    document.getElementById("star1").className = "fa fa-star checked";    
	}

	document.getElementById("ratingSelect").value="1";
	
    }

    function ratingChecked2(){
	if(document.getElementById("star2").className == "fa fa-star checked"){
	    document.getElementById("star5").className = "fa fa-star";
	    document.getElementById("star4").className = "fa fa-star";
	    document.getElementById("star3").className = "fa fa-star";
	}else{
	    document.getElementById("star1").className = "fa fa-star checked";
	    document.getElementById("star2").className = "fa fa-star checked";
	}

	document.getElementById("ratingSelect").value="2";

    }

    function ratingChecked3(){
	if(document.getElementById("star3").className == "fa fa-star checked"){
	    document.getElementById("star5").className = "fa fa-star";
	    document.getElementById("star4").className = "fa fa-star";
	}else{
	    document.getElementById("star1").className = "fa fa-star checked";
	    document.getElementById("star2").className = "fa fa-star checked";
	    document.getElementById("star3").className = "fa fa-star checked";
	}

	document.getElementById("ratingSelect").value="3";

    }

    function ratingChecked4(){
	if(document.getElementById("star4").className == "fa fa-star checked"){
	    document.getElementById("star5").className = "fa fa-star";
	}else{
	    document.getElementById("star1").className = "fa fa-star checked";
	    document.getElementById("star2").className = "fa fa-star checked";
	    document.getElementById("star3").className = "fa fa-star checked";
	    document.getElementById("star4").className = "fa fa-star checked";
	}

	document.getElementById("ratingSelect").value="4";

    }

    function ratingChecked5(){
	if(!(document.getElementById("star5").className == "fa fa-star checked")){
	    document.getElementById("star1").className = "fa fa-star checked";
	    document.getElementById("star2").className = "fa fa-star checked";
	    document.getElementById("star3").className = "fa fa-star checked";
	    document.getElementById("star4").className = "fa fa-star checked";
	    document.getElementById("star5").className = "fa fa-star checked";
	}

	document.getElementById("ratingSelect").value="5";

    }
    
  </script>
</html>